controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#defind route

accueil:
    path: /
    controller: App\Controller\AccueilController::index

boutique:
    path: /boutique
    controller: App\Controller\BoutiqueController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

detail:
    path: /detail
    controller: App\Controller\DetailController::index

espaceclient:
    path: /espaceclient
    controller: App\Controller\EspaceClientController::index

keylaboratory:
    path: /keylaboratory
    controller: App\Controller\KeyLaboratoryController::index


    
